MODEL:
  TYPE: ResNet
  IMG_SIZE: 224
  NUM_CLASSES: 100
CNN:
  DEPTH: 56
RESNET:
  TRANS_FUN: basic_transform
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: imagenet_100
  SPLIT: train
  BATCH_SIZE: 256
  MIXED_PRECISION: True
TEST:
  DATASET: imagenet_100
  SPLIT: val
  BATCH_SIZE: 256
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False
